
// PLUGIN VERSIONS MUST BE SPECIFIED AT THE ROOT LEVEL (BUT DO NOT APPLY)
plugins {
	id 'io.freefair.lombok' version "${version_plugin_lombok}" apply false
	id 'com.diffplug.spotless' version "${version_plugin_spotless}" apply false
	id 'com.google.cloud.tools.jib' version "${version_plugin_jib}" apply false
	id 'org.springframework.boot' version "${version_spring_boot}" apply false
}
