##################
## JAVA VERSION ##
##################
javaLanguageVersion=21

##############
## ARTIFACT ##
##############
group=com.robindrew.services
version=1.0.0-SNAPSHOT

#######################
## GRADLE PROPERTIES ##
#######################
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

##############
## VERSIONS ##
##############
version_robindrew_core=3.9.0

version_plugin_jib=3.4.5
version_plugin_spotless=7.0.2
version_plugin_lombok=8.14
version_lombok=1.18.38
version_spring_boot=3.4.8
version_docker=3.4.0
version_guava=33.4.8-jre
version_jfreechart=1.5.6
version_velocity_engine=2.4.1
version_freemarker=2.3.34
version_oshi_core=6.2.2
version_commons_codec=1.19.0
version_simple_xml=2.7.1
version_sysout_over_slf4j=1.0.2
version_trove4j=3.0.3
version_httpclient=4.5.2
version_springdoc_webmvc=2.8.1
version_aws=2.32.16
version_opencsv=5.12.0
version_nimbus_jose_jwt=9.48
version_commons_compress=1.27.1