
#############
## SERVICE ##
#############
service.profiles ${spring.profiles.active}


################
## WEB SERVER ##
################
server.port	${service.port}


#####################
## STATS COMPONENT ##
#####################
stats.component.frequency-period 5
stats.component.frequency-unit    MINUTES
stats.component.cache-capacity  1000

