
#############
## SERVICE ##
#############
server.port=7700


#############
## OPENAPI ##
#############
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


###################
## AUTHORIZATION ##
###################
auth.username=admin
auth.password=admin


#########
## PTF ##
#########
ptf.directory=C:/data/trading/ptf


#########
## PCF ##
#########
pcf.directory=C:/data/trading/pcf
